# Golang CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-go/ for more details
# tags DOCS: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
version: 2
jobs:
  build:
    docker:
        - image: ubuntu:18.04
    working_directory: ~/stuff/notgopath/sir
    steps:
        - checkout
        - run:
            name: install apt and pip deps
            command: |
                pwd; ls -lsha
                apt-get -y update
                apt -y install \
                            curl \
                            wget \
                            git \
                            build-essential \
                            nano

        - run:
            name: install golang
            command: |
                VER="go1.11"
                wget --directory-prefix=/usr/local https://dl.google.com/go/$VER.linux-amd64.tar.gz
                tar -C /usr/local -xzf /usr/local/$VER.linux-amd64.tar.gz
                export PATH=$PATH:/usr/local/go/bin
                echo "export PATH=$PATH:/usr/local/go/bin" >> /etc/profile
                mkdir -p ~/go/bin
                echo "export PATH=$PATH:~/go/bin" >> /etc/profile
                echo "export LC_ALL=C.UTF-8" >> /etc/profile
                echo "export LANG=C.UTF-8" >> /etc/profile
                echo "export GO111MODULE=on" >> /etc/profile
                source /etc/profile

        - run:
            name: install tools
            command: |
                source /etc/profile
                GOBIN_VERSION=v0.0.4
                wget -nc --directory-prefix=/tmp https://github.com/myitcv/gobin/releases/download/$GOBIN_VERSION/linux-amd64
                mv /tmp/linux-amd64 /usr/local/bin/gobin
                chmod +x /usr/local/bin/gobin
                gobin honnef.co/go/tools/cmd/staticcheck@2019.1

        - run: source /etc/profile && go build --race -o sir cmd/main.go
        # - run: ./sir -v

        - run:
            name: go vet
            command: source /etc/profile && go vet -v -all -shadow ./...
        - run:
            name: staticcheck
            command: source /etc/profile && staticcheck -tests -show-ignored ./...
        - run:
            name: run tests
            command: source /etc/profile && go test -timeout 1m -race -cover -v ./...
        - run:
            name: run benchmarks
            command: source /etc/profile && go test -timeout 1m -race -run=XXXX -bench=. ./...
        - run:
            name: codecov
            command: |
                source /etc/profile && \
                go test -timeout 1m -v -race -cover -coverprofile=coverage.txt ./... && \
                bash <(curl -s https://codecov.io/bash)

  deploy:
    docker:
        - image: ubuntu:18.04
    working_directory: ~/stuff/notgopath/sir
    steps:
        - checkout
        - run:
            name: something
            command: |
                printf "do some deploy stuff"


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/